FrontEnd/Areas/AI/Controllers/CobController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FrontEnd.Areas.AI.Controllers
{
    public class CobController : Controller
    {
        public IActionResult CobReview()
        {
            if (!User.Identity.IsAuthenticated)
            {
                Redirect("/Login");
            }
            else
            {
                if(!User.IsInRole("Cob") || !User.IsInRole("Dev"))
                {
                    Redirect("/AccessDenied");
                }
            }

            return RedirectToPage("CobReview");
            
        }
    }
}

FrontEnd/Areas/Cob/Pages/CobReview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FrontEnd.Areas.Cob.Pages
{
    public class CobReviewModel : PageModel
    {
        public void OnGet()
        {
            if(!User.IsInRole("Cob") || !User.IsInRole("Dev"))
            {
                RedirectToPage("/AccessDenied");
            }
        }
    }
}

FrontEnd/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Eventing.Reader;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Web;
using System.Net;
using System.Security.Claims;
using System.Security.Principal;
using System.Threading.Tasks;
using FrontEnd.Views;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace FrontEnd.Controllers
{
    public class AuthController : Controller
    {

        [Route("Login")]
        public IActionResult Login(string returnURL)
        {

            var userinfo = new Login();

            try
            {
                EnsureLogOut();

                userinfo.ReturnUrl = returnURL;

                return View(userinfo);
            }
            catch (Exception)
            {

                throw;
            }

        }

        private void EnsureLogOut()
        {
            if (User.Identity.IsAuthenticated)
            {
                Logout();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        private void Logout()
        {
            SignOut();

            //Empty the users logged in details
            HttpContext.User = new ClaimsPrincipal(new ClaimsIdentity());

            // Clear the session cache to help prevent MIM attacks
            HttpContext.Session.Clear();

            RedirectToLocal();


        }

        

        private ActionResult RedirectToLocal(string returnUrl = "")
        {
            try
            {
                if(!string.IsNullOrWhiteSpace(returnUrl) && Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    return RedirectToPage("Index");
                }
            }
            catch (Exception)
            {

                throw;
            }
        }

        [Route("ValidateUser")]
        public IActionResult ValidateUser(string username, string password, string redirectLocation)
        {

            //Open connection to the ms.ds active directory
            using (var pc = new PrincipalContext(ContextType.Domain, "ms.ds.uhc.com", null, ContextOptions.Negotiate))
            {
                //validate user
                if (!pc.ValidateCredentials(username, password))
                {
                    //Get user details
                    var user = UserPrincipal.FindByIdentity(pc, username);
                    //If unable to find user on the system then return forbiden
                    if (user == null)
                    {
                        return Unauthorized();
                    }
                    ///Create an identity store for the users roles
                    var id = new ClaimsIdentity();

                    id.AddClaim(new Claim(ClaimTypes.Upn, user.UserPrincipalName));
                    id.AddClaim(new Claim("http://schemas.microsoft.com/accesscontrolservice/2010/07/claims/identityprovider", "ASP.NET Identity", "http://www.w3.org/2001/XMLSchema#string"));
                    id.AddClaim(new Claim(ClaimTypes.Name, user.GivenName));
                    id.AddClaim(new Claim(ClaimTypes.Email, user.EmailAddress));
                    id.AddClaim(new Claim(ClaimTypes.WindowsAccountName, username));

                    var groups = user.GetGroups();

                    var roles = groups.Select(x => new Claim(ClaimTypes.Role, x.Name));
                    id.AddClaims(roles);

                    User.AddIdentity(id);

                    return RedirectToRoute(redirectLocation);
                }
                return Unauthorized();
            }
        }
    }
}

FrontEnd/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FrontEnd.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

FrontEnd/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FrontEnd.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

FrontEnd/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace FrontEnd.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

FrontEnd/Areas/Cob/Pages/CobReview.cshtml
@page

@model FrontEnd.Areas.Cob.Pages.CobReviewModel
@{
    ViewData["Title"] = "Cob Review";

    if (User.Identity.IsAuthenticated)
    {
        
    }

}

<div>

</div>

FrontEnd/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FrontEnd/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">FrontEnd</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Cob" asp-controller="Cob" asp-action="CobReview" >Cob Review </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FrontEnd - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

FrontEnd/Views/Login.cshtml
@model FrontEnd.Views.Login
@{
    ViewData["Title"] = "Login";
}

@using (Html.BeginForm("Login", "Auth", FormMethod.Post))
{
    @Html.AntiForgeryToken();
    @Html.HiddenFor(s => s.ReturnUrl)

    <h1>Login</h1>
    <h3>Please enter your MSID and Password</h3>
    <div>
        @if (TempData["ErrorMSG"] != null)
        {
            <label style="color:maroon;"> @TempData["ErrorMSG"] </label>
            <br /><br />
        }

        @Html.TextBoxFor(s => s.Username, new { @placeholder = "Username" })
        <br /> <br />
        @Html.PasswordFor(s => s.Password, new { @placeholder = "Password" })
        <br /> <br />
        
        <br /> <br />
        <button type="submit">Login</button>
    </div>
}